<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>tact</string>
    <key>scopeName</key>
    <string>source.tact</string>
    <key>fileTypes</key>
    <array>
      <string>tact</string>
    </array>
    <key>foldingStartMarker</key>
    <string>\{s*$</string>
    <key>foldingStopMarker</key>
    <string>^\s*\}</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#struct</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#contract-or-trait</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#annotation</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#fun-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#const-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#statements</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>import</key>
      <dict>
        <key>name</key>
        <string>meta.import.tact</string>
        <key>begin</key>
        <string>(?&lt;![_$[:alnum:]])(?:(?&lt;=\.\.\.)|(?&lt;!\.))\b(import)\b\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.import.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.tact</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
        </array>
      </dict>
      <key>struct</key>
      <dict>
        <key>name</key>
        <string>meta.struct.tact</string>
        <key>begin</key>
        <string>(?&lt;![_$[:alnum:]])(?:(?&lt;=\.\.\.)|(?&lt;!\.))\b(struct|message)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.struct</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-header</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-body</string>
          </dict>
        </array>
      </dict>
      <key>struct-header</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[\w]+\b</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.tact</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\(((?:\b0(?:x|X)[0-9a-fA-F][0-9a-fA-F_]*\b)|(?:\b[0-9]+\b))\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>struct-body</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.tact</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#field-declaration</string>
          </dict>
        </array>
      </dict>
      <key>contract-or-trait</key>
      <dict>
        <key>name</key>
        <string>meta.struct.tact</string>
        <key>begin</key>
        <string>(?&lt;![_$[:alnum:]])(?:(?&lt;=\.\.\.)|(?&lt;!\.))\b(contract|trait)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.struct</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.with.tact</string>
            <key>match</key>
            <string>with</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type.tact</string>
            <key>match</key>
            <string>\b[\w]+\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#contract-or-trait-body</string>
          </dict>
        </array>
      </dict>
      <key>contract-or-trait-body</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.tact</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#init-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#receive-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#bounce-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fun-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#const-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#field-declaration</string>
          </dict>
        </array>
      </dict>
      <key>field-declaration</key>
      <dict>
        <key>name</key>
        <string>meta.struct.field.tact</string>
        <key>begin</key>
        <string>(\b[\w]+\b)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.object.property.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.tact</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-annotation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable-init</string>
          </dict>
        </array>
      </dict>
      <key>const-declaration</key>
      <dict>
        <key>name</key>
        <string>meta.struct.field.tact</string>
        <key>begin</key>
        <string>(?=\b(?:(?:get|native|extends|mutates|virtual|override|inline|abstract)\s*)*const\b)</string>
        <key>end</key>
        <string>(;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.tact</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.tact</string>
            <key>match</key>
            <string>const</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.modifier.tact</string>
            <key>match</key>
            <string>\b(get|native|extends|mutates|virtual|override|inline|abstract)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.name.tact</string>
            <key>match</key>
            <string>\b[\w]+\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-annotation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable-init</string>
          </dict>
        </array>
      </dict>
      <key>init-declaration</key>
      <dict>
        <key>name</key>
        <string>meta.struct.field.tact</string>
        <key>begin</key>
        <string>(init)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.init.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fun-arguments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-declaration</string>
          </dict>
        </array>
      </dict>
      <key>receive-declaration</key>
      <dict>
        <key>name</key>
        <string>meta.struct.field.tact</string>
        <key>begin</key>
        <string>(receive|external)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.receive.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fun-arguments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-declaration</string>
          </dict>
        </array>
      </dict>
      <key>bounce-declaration</key>
      <dict>
        <key>name</key>
        <string>meta.struct.field.tact</string>
        <key>begin</key>
        <string>(bounced)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.bounce.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fun-arguments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-declaration</string>
          </dict>
        </array>
      </dict>
      <key>fun-declaration</key>
      <dict>
        <key>name</key>
        <string>meta.function.tact</string>
        <key>begin</key>
        <string>(?=\b(?:(?:get|native|extends|mutates|virtual|override|inline|abstract)\s*)*fun\b)</string>
        <key>end</key>
        <string>(?&lt;=\}|;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.tact</string>
            <key>match</key>
            <string>fun</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.modifier.tact</string>
            <key>match</key>
            <string>\b(get|native|extends|mutates|virtual|override|inline|abstract)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.definition.function.tact entity.name.function.tact</string>
            <key>match</key>
            <string>(\b[\w]+\b)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fun-declaration-body</string>
          </dict>
        </array>
      </dict>
      <key>fun-declaration-body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fun-arguments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-annotation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-declaration</string>
          </dict>
        </array>
      </dict>
      <key>fun-arguments</key>
      <dict>
        <key>name</key>
        <string>meta.parameters.tact</string>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.begin.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.end.tact</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-annotation</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:(self)|(\b[\w]+\b))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.language.self.tact</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.name.tact</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>block-declaration</key>
      <dict>
        <key>name</key>
        <string>meta.block.tact</string>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.begin.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.end.tact</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#statements</string>
          </dict>
        </array>
      </dict>
      <key>statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>annotation</key>
      <dict>
        <key>name</key>
        <string>meta.annotation.tact</string>
        <key>begin</key>
        <string>(@)([\w_]+)(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.annotation.tact</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.annotation.tact</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.annotation.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.annotation.tact</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#annotation-argument</string>
          </dict>
        </array>
      </dict>
      <key>annotation-argument</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[\w_]+</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.tact</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>expressions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numeric</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-annotation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-init</string>
          </dict>
        </array>
      </dict>
      <key>struct-init</key>
      <dict>
        <key>name</key>
        <string>meta.struct.init</string>
        <key>begin</key>
        <string>(\b[\w]+\b)\s*(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.tact</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.begin.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.end.tact</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-property</string>
          </dict>
        </array>
      </dict>
      <key>struct-property</key>
      <dict>
        <key>name</key>
        <string>meta.struct.init.property,</string>
        <key>begin</key>
        <string>(\b[\w]+\b)\s*(:)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.name.tact</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.property.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\}|\,)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>variable-init</key>
      <dict>
        <key>name</key>
        <string>meta.variable.property.init</string>
        <key>begin</key>
        <string>(=)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\}|\{|\,|\;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>type-annotation</key>
      <dict>
        <key>name</key>
        <string>meta.type.annotation.tact</string>
        <key>begin</key>
        <string>(:)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.type.annotation.tact</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\{|\;|\=|\,|\))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-as</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-generic</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.optional.tact</string>
            <key>match</key>
            <string>\?</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[\w]+\b</string>
            <key>name</key>
            <string>entity.name.type.tact</string>
          </dict>
        </array>
      </dict>
      <key>type-generic</key>
      <dict>
        <key>name</key>
        <string>meta.type.generics.tact</string>
        <key>begin</key>
        <string>&lt;</string>
        <key>end</key>
        <string>&gt;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-as</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.tact</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[\w]+\b</string>
            <key>name</key>
            <string>entity.name.type.tact</string>
          </dict>
        </array>
      </dict>
      <key>type-as</key>
      <dict>
        <key>name</key>
        <string>meta.type.annotation.as.tact</string>
        <key>begin</key>
        <string>(as)\s+</string>
        <key>end</key>
        <string>(?=\{|\;|\=|\,|\)|\&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.as.tact</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[\w]+\b</string>
            <key>name</key>
            <string>storage.modifier.tact</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.tact</string>
            <key>match</key>
            <string>\b(if|else|while|do|until|repeat|return|extends|mutates|virtual|override|inline|native|let|const|fun|self|is|initOf|map|bounced|get|as)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
            <key>match</key>
            <string>(?&lt;=\s)(&lt;=&gt;|&gt;=|&lt;=|!=|==|\^&gt;&gt;|\~&gt;&gt;|&gt;&gt;|&lt;&lt;|\/%|\^%|\~%|\^\/|\~\/|\+=|-=|\*=|\/=|~\/=|\^\/=|%=|\^%=|&lt;&lt;=|&gt;&gt;=|~&gt;&gt;=|\^&gt;&gt;=|&amp;=|\|=|\^=|\^|=|~|\/|%|-|\*|\+|&gt;|&lt;|&amp;|\||:|\?)(?=\s)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other</string>
            <key>match</key>
            <string>\b(false|true)\b</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.tact</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
      </dict>
      <key>numeric</key>
      <dict>
        <key>name</key>
        <string>constant.numeric</string>
        <key>match</key>
        <string>(?:\b0(?:x|X)[0-9a-fA-F][0-9a-fA-F_]*\b)|(?:\b[0-9]+\b)</string>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line</string>
            <key>match</key>
            <string>\/\/(.*)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[\w]+\b(?!\s*\()(?!\s*\{)</string>
            <key>name</key>
            <string>variable.name.tact</string>
          </dict>
        </array>
      </dict>
      <key>function-call</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[\w]+\b(?=\s*\()(?!\s*\{)</string>
            <key>name</key>
            <string>entity.name.function.tact</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>